In [ ]:
#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
#importing data'
df=pd.read_excel('/content/salaries2.xlsx', header=2)

In [ ]:
df=pd.DataFrame(df)

In [ ]:
df.shape

(975, 252)

In [ ]:
df.head()

,كود المنطقة,كود الادارة,الادارة,الكود,الاسم,الجنسية,الرقم القومي,رقم جواز السفر,رقم التليفون,حالة تصريح العمل لغير المصريين,...,Unnamed: 242,Unnamed: 243,Unnamed: 244,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251
0,1,4,الشئون الأدارية,260,عبدالرؤوف عبدالحميد السعدني,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,4,الشئون الأدارية,881,فاتن عبدالرحمن محمد,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,4,الشئون الأدارية,1064,سعيد محمد عبد الله,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,الشئون الأدارية,2301,حسن فؤاد أحمد محمد,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,4,الشئون الأدارية,2530,عايدة خطاب ابراهيم,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#droping confidential columns
#checking for nulls
#handling nulls values and columns
#checking duplicates
#checking for data type
#changing data type
#standarlizing values

In [ ]:
#droping confidental data (empty columns)

df=df.drop(columns=['الرقم القومي'])
df=df.drop(columns=['رقم التسجيل الضريبي لجهة العمل الأصلية'])
df=df.drop(columns=['رقم جواز السفر'])
df=df.drop(columns=['رقم التليفون'])
df=df.drop(columns=['حالة تصريح العمل لغير المصريين'])
df=df.drop(columns=['رقم تصريح العمل'])

In [ ]:
#removing empty rows having no cells
df.reset_index(drop=True, inplace=True)
df.index += 1

In [ ]:
df.head()

,كود المنطقة,كود الادارة,الادارة,الكود,الاسم,الجنسية,الوظيفة,اسم الجهة/الفرع,المعاملة الضريبية,مدة العمل,...,Unnamed: 242,Unnamed: 243,Unnamed: 244,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251
1,1,4,الشئون الأدارية,260,عبدالرؤوف عبدالحميد السعدني,1,مدير إدارة شئون العاملين والوثائق والمحفوظات,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,4,الشئون الأدارية,881,فاتن عبدالرحمن محمد,1,أخصائي شئون عاملين أول,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,الشئون الأدارية,1064,سعيد محمد عبد الله,1,سائق أول,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,4,الشئون الأدارية,2301,حسن فؤاد أحمد محمد,1,عامل خدمات رابع,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,4,الشئون الأدارية,2530,عايدة خطاب ابراهيم,1,أخصائي تخطيط ثالث,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#handling columns name without any spaces
df.columns=df.columns.str.strip()

In [ ]:
#removing unamed columns
df.drop(columns=df.columns[df.columns.str.contains('^Unnamed')], inplace=True)

In [ ]:
#data after removing non used columns :
df.shape

(975, 193)

In [ ]:
df_filtered=df.copy()

In [ ]:
#checking for nulls in data
df.isnull().sum()

كود المنطقة                     409
كود الادارة                     306
الادارة                         400
الكود                           444
الاسم                           438
                               ...
العلاوة الخاصة 5%               412
مجموع العلاوات 10%&%5%          412
فرق 150                         412
العلاوه الخاصه 7/2025           409
مجموع العلاوات الخاصة 7/2025    410
Length: 193, dtype: int64

In [ ]:
#handing missing values, removing empty rows in employee names columns :
df=df.dropna(subset=['الاسم'])
df=df.dropna(subset=['الادارة'])
dept=df['الادارة']

In [ ]:
df = df[
    dept.notna() &
    (~dept.astype(str).str.strip().str.startswith('اجمالى')) &
    (dept.astype(str).str.strip() != 'أسم العامل')]

/tmp/ipython-input-2663554335.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

In [ ]:
df['الادارة'].nunique()

49

In [ ]:
df=df.dropna(subset=['كود الادارة'])

In [ ]:
df.isnull().sum()

كود المنطقة           0
كود الادارة           0
الادارة               0
الكود                 0
الاسم                 0
                   ...
total_salaries        0
total_deductions      0
employee_numbers      0
employee_counts       0
Employees_by_dpt    509
Length: 201, dtype: int64

In [ ]:
#checking for duplicates
df.duplicated().sum()

#removing duplicates
df.drop_duplicates(inplace=True)

In [ ]:
#checking for duplicates after removing them
df.duplicated().sum()

np.int64(0)

In [ ]:
#data after handling nulls and duplicates
df.shape

(509, 201)

In [ ]:
#checking for data types
df.dtypes.sort_values()

employee_counts       int64
employee_numbers      int64
تأمينات العامل.5    float64
خصومات متنوعه.6     float64
الصافي.6            float64
                     ...
الجنسية              object
الوظيفة              object
حالة العمل           object
deduction_ratio      object
كود المنطقة          object
Length: 201, dtype: object

In [ ]:
#checking for data types
text_values=df_filtered.select_dtypes(include='object').columns.tolist()
print(text_values)

['كود المنطقة', 'كود الادارة', 'الادارة', 'الكود', 'الاسم', 'الجنسية', 'الوظيفة', 'اسم الجهة/الفرع', 'حالة العمل', 'salary_category', 'deduction_ratio']

In [ ]:
#checking for numeric columns
numeric_values=df.select_dtypes(include='number').columns.tolist()
print(numeric_values)

['المعاملة الضريبية', 'مدة العمل', 'الحالة التأمينية', 'الرقم التأمينى', 'تاريخ الالتحاق بالتأمينات', 'الضرائب المراد خصمها', 'صندوق الشهداء', 'علاوات خاصة معفاة', 'الاساسي المجرد من العلاوات', 'الأساسي', 'بدل الطبيعة', 'بدل الوجبة', 'منحة العمال', 'اعانة اجتماعية', 'علاوة أضافية', 'تمثيل', 'انتقال', 'مشروب', 'بدل تفرغ', 'علاوة غلاء', 'اجمالى العام العلاوات', 'الحد الادنى', 'مفردات اجمالى استحقاقات الراتب', 'بدلات غير خاضعة تأمينيا', 'الاجمالى الخاضع للتامينات', 'اجمالى التامينات للعامل', 'اجمالى التأمينات لصاحب العمل', 'اجازات مدفوعة\nس', 'الاجازات المرضى\n100% مستشفى \nس', 'الاجازات المرضى\n75% مستشفى \nس', 'الاجازات المرضى\n50% مستشفى \nس', 'الاجازات المرضى\n100%\nس', 'الغياب\nس', 'الجزاءات\nس', 'أضافى \n100%', 'أضافى \n125%', 'أضافى \n150%', 'أساسى 3/2024', 'بدل الطبيعة .1', 'بدل الوجبة.1', 'منحة العمال.1', 'اعانة اجتماعية.1', 'علاوة أضافية', 'تمثيل.1', 'انتقال.1', 'المشروب', 'بدل تفرغ.1', 'العلاوات', 'الحد الادنى', 'الاضافى', 'اجمالى المستحق', 'الوعاء التأميني', 'حصة تأمينات العامل', 'حصة تأمينات صاحب العمل', 'ضرائب كسب العمل', 'المرضي %75', 'المرضي %50', 'أشتراك علاج أسر', 'قسط علاج أسر\nح/289415', 'قيمة ضم مده\nح/28452', 'قسمه صندوق الجزاءات و الغرامات', 'نادى الشركة', 'نقابة مهنية', 'صندوق الأعاقة', 'صندوق الشهداء.1', 'صندوق زمالة', 'نفقة شهرية\nح/289418', 'المصيف', 'عدد ساعات الخصم', 'اقساط بنوك\nح/289416', 'ساعات  خصم\nح/321', 'مخالفات مرور\nح/3543', 'سلف  شخصية', 'أستقطاعات متنوعة\nاخرى', 'اجمالى الأستقطاعات المتنوعة', 'اجمالى الأستقطاعات', 'صافى الراتب', 'معامل \nحافز الانتاج', 'عدد ايام الحضور', 'اجمالى حافز الانتاج', 'ضرائب كسب العمل.1', 'تأمينات عامل', 'تأمينات صاحب العمل', 'خصومات متنوعه', 'الصافي', 'اجمالى حافز خاص', 'ضرائب كسب العمل.2', 'تأمينات صاحب العمل.1', 'تأمينات العامل', 'خصومات متنوعه.1', 'الصافي.1', 'اجمالى المكافأت و التسويات', 'ضرائب كسب العمل.3', 'تأمينات صاحب العمل.2', 'تأمينات العامل.1', 'خصومات متنوعه.2', 'الصافي.2', 'اجمالى المكافأت و التسويات.1', 'ضرائب كسب العمل.4', 'تأمينات صاحب العمل.3', 'تأمينات العامل.2', 'خصومات متنوعه.3', 'الصافي.3', 'اجمالى المكافأت و التسويات.2', 'ضرائب كسب العمل.5', 'تأمينات صاحب العمل.4', 'تأمينات العامل.3', 'خصومات متنوعه.4', 'الصافي.4', 'اجمالى المكافأت و التسويات.3', 'ضرائب كسب العمل.6', 'تأمينات صاحب العمل.5', 'تأمينات العامل.4', 'خصومات متنوعه.5', 'الصافي.5', 'اجمالى المكافأت و التسويات.4', 'ضرائب كسب العمل.7', 'تأمينات صاحب العمل.6', 'تأمينات العامل.5', 'خصومات متنوعه.6', 'الصافي.6', 'اجمالى المكافأت و التسويات.5', 'ضرائب كسب العمل.8', 'تأمينات صاحب العمل.7', 'تأمينات العامل.6', 'خصومات متنوعه.7', 'الصافي.7', 'اجمالى المكافأت و التسويات.6', 'ضرائب كسب العمل.9', 'تأمينات صاحب العمل.8', 'تأمينات العامل.7', 'خصومات متنوعه.8', 'الصافي.8', 'اجمالى المكافأت و التسويات.7', 'ضرائب كسب العمل.10', 'تأمينات صاحب العمل.9', 'تأمينات العامل.8', 'خصومات متنوعه.9', 'الصافي.9', 'اجمالى المكافأت و التسويات.8', 'ضرائب كسب العمل.11', 'تأمينات صاحب العمل.10', 'تأمينات العامل.9', 'خصومات متنوعه.10', 'الصافي.10', 'اجمالى المكافأت و التسويات.9', 'ضرائب كسب العمل.12', 'تأمينات صاحب العمل.11', 'تأمينات العامل.10', 'خصومات متنوعه.11', 'الصافي.11', 'اجمالى المكافأت و التسويات.10', 'ضرائب كسب العمل.13', 'تأمينات صاحب العمل.12', 'تأمينات العامل.11', 'خصومات متنوعه.12', 'الصافي.12', 'اجمالى المكافأت و التسويات.11', 'ضرائب كسب العمل.14', 'تأمينات صاحب العمل.13', 'تأمينات العامل.12', 'خصومات متنوعه.13', 'الصافي.13', 'اجمالى المكافأت و التسويات.12', 'ضرائب كسب العمل.15', 'تأمينات صاحب العمل.14', 'تأمينات العامل.13', 'خصومات متنوعه.14', 'الصافي.14', 'اجمالى المكافأت و التسويات.13', 'ضرائب كسب العمل.16', 'تأمينات صاحب العمل.15', 'تأمينات العامل.14', 'خصومات متنوعه.15', 'الصافي.15', 'الدرجة الوظيفية', 'معامل حافز الانتاج', 'قيمة 10%علاوة دورية', 'الاساسي  1/7/2025', 'العلاوة الخاصة 5%', 'مجموع العلاوات 10%&%5%', 'فرق 150', 'العلاوه الخاصه 7/2025', 'مجموع العلاوات الخاصة 7/2025', 'total_allowances', 'total_salaries', 'total_deductions', 'employee_numbers', 'employee_counts', 'Employees_by_dpt']

In [ ]:
#data type maniplulation
df['الاساسي المجرد من العلاوات']=pd.to_numeric(df['الاساسي المجرد من العلاوات'], errors='coerce')
df['المعاملة الضريبية']=pd.to_numeric(df['المعاملة الضريبية'],errors='coerce')
df['اجمالى المستحق']=pd.to_numeric(df['اجمالى المستحق'],errors='coerce')
df['اجمالى الأستقطاعات']=pd.to_numeric(df['اجمالى الأستقطاعات'],errors='coerce')

In [ ]:
df['deduction_ratio']=pd.to_numeric(df['deduction_ratio'],errors='coerce')

In [ ]:
df['الاسم'].nunique()

509

In [ ]:
def salary_category(salary):
  if salary >= 5000:
    return "HIGH"
  elif salary  >=3000:
    return "Meduim"
  else:
    return"low"

df['salary_category']=df['صافى الراتب'].apply(salary_category)

In [ ]:
total_allowances=df['اجمالى حافز الانتاج'].sum()
total_salaries=df['اجمالى المستحق'].sum()
total_deductions=df['اجمالى الأستقطاعات'].sum()

In [ ]:
df['total_allowances']=total_allowances
df['total_salaries']=total_salaries
df['total_deductions']=total_deductions

In [ ]:
#allowance percentatge
reduction_percentatge=((total_deductions/total_salaries)*100)
print(reduction_percentatge)

14.625450817478965

In [ ]:
allowance_percentatge=(total_allowances/total_salaries)*100

print(allowance_percentatge)

16.412548514857804

In [ ]:
employee_numbers=df['الاسم'].nunique()

In [ ]:
df.groupby('salary_category')['employee_numbers'].count()

salary_category
HIGH      381
Meduim     71
low        57
Name: employee_numbers, dtype: int64

In [ ]:
df_filtered=df.copy()

In [ ]:
cols_to_keep = ['الاسم', 'الوظيفة', 'الكود', 'الادارة', 'كود الادارة','salary_category',
                'صافى الراتب','اجمالى الأستقطاعات','اجمالى المستحق','deduction_ratio', 'اجمالى حافز الانتاج','الجزاءات\nس']

In [ ]:
df_filtered.isnull().sum()

كود المنطقة           0
كود الادارة           0
الادارة               0
الكود                 0
الاسم                 0
                   ...
total_salaries        0
total_deductions      0
employee_numbers      0
employee_counts       0
Employees_by_dpt    509
Length: 201, dtype: int64

In [ ]:
df_filtered=pd.DataFrame(df_filtered)

In [ ]:

df_filtered.reset_index(drop=True, inplace=True)
df_filtered.index += 1

In [ ]:
df_filtered.head()

,كود المنطقة,كود الادارة,الادارة,الكود,الاسم,الجنسية,الوظيفة,اسم الجهة/الفرع,المعاملة الضريبية,مدة العمل,...,العلاوه الخاصه 7/2025,مجموع العلاوات الخاصة 7/2025,salary_category,deduction_ratio,total_allowances,total_salaries,total_deductions,employee_numbers,employee_counts,Employees_by_dpt
1,1,4,الشئون الأدارية,260,عبدالرؤوف عبدالحميد السعدني,1,مدير إدارة شئون العاملين والوثائق والمحفوظات,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,137.60750,1373.69750,Meduim,50.18%,487091.265618,2.967798e+06,434053.818179,512,512,NaN
2,1,4,الشئون الأدارية,881,فاتن عبدالرحمن محمد,1,أخصائي شئون عاملين أول,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,138.66500,1527.98500,low,nan%,487091.265618,2.967798e+06,434053.818179,512,512,NaN
3,1,4,الشئون الأدارية,1064,سعيد محمد عبد الله,1,سائق أول,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,145.63700,1503.87700,HIGH,21.18%,487091.265618,2.967798e+06,434053.818179,512,512,NaN
4,1,4,الشئون الأدارية,2301,حسن فؤاد أحمد محمد,1,عامل خدمات رابع,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,60.60266,737.53266,HIGH,10.65%,487091.265618,2.967798e+06,434053.818179,512,512,NaN
5,1,4,الشئون الأدارية,2530,عايدة خطاب ابراهيم,1,أخصائي تخطيط ثالث,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,72.45077,819.54077,HIGH,11.03%,487091.265618,2.967798e+06,434053.818179,512,512,NaN

In [ ]:
employee_counts=df['الاسم'].count()

In [ ]:
df['employee_counts']=employee_counts

In [ ]:
employee_counts

np.int64(509)

In [ ]:
Employees_by_dpt=df.groupby('الادارة')['employee_counts'].count().sort_values(ascending=False)

In [ ]:
df['Employees_by_dpt']=Employees_by_dpt

In [ ]:

Employees_by_dpt

الادارة
التغليف                 32
الاحتياجات              30
الشئون الأدارية         27
التشغيل الهندسي         25
الأمن و الحراسة         25
مصنع معلبات أ           23
مصنع معلبات ب           19
مؤقتين شئون أدارية      18
التجميد                 17
مصنع الصفيح             17
الأدارة المالية         17
مؤقتين أحتياجات         16
مؤقتين معلبات ب         14
معامل و بحوث            14
مؤقتين معامل و بحوث     14
الحضانة                 14
القسم الهندسي           13
مؤقتين تغليف            13
مؤقتين الحضانة          12
مؤقتين تجميد            10
مؤقتين مالية            10
مؤقتين معلبات أ         10
مؤقتين أمن و حراسة       9
الامن الصناعى            9
التبريدات                9
مؤقتين الزجاج            9
مصنع الزجاج              8
مؤقتين الصفيح            7
مؤقتين القسم الهندسي     6
ألبان دمياط              6
مكتب القاهرة             5
المبيعات                 5
مؤقتين مبيعات            5
مستلزمات الانتاج         5
القفل                    4
مؤقتين تشغيل هندسي       4
الشئون القانونية         4
سكرتارية                 3
مؤقتين أمن صناعي         3
التجهيز و التعبئة        3
مؤقتين بضاعة جاهزة       3
مؤقتين مكتب القاهرة      3
الحسابات                 2
الصيانة                  2
جودة المعمل              1
مؤقتين تبريدات           1
مؤقتين المرتجعات         1
سيارات نقل               1
مكتب أسيوط               1
Name: employee_counts, dtype: int64

In [ ]:
df.shape

(509, 201)

In [ ]:

df_filtered['صافى الراتب']=pd.to_numeric(df_filtered['صافى الراتب'], errors='coerce')

In [ ]:
#top 5 departments costly in the company
df.groupby('الادارة')['صافى الراتب'].sum().nlargest(5)

الادارة
الأمن و الحراسة    144258.474991
التغليف            143573.163533
الاحتياجات         134034.689877
التشغيل الهندسي    126123.412539
مصنع معلبات أ      124513.988994
Name: صافى الراتب, dtype: float64

In [ ]:
#موظف صاحب اعلي حافز انتاج

df.groupby('الاسم')['اجمالى حافز الانتاج'].sum().nlargest(2)

الاسم
سـعد السـيد محمـد علي             3714.967667
علاء الدين محمد محمد الطحان       3649.733333
Name: اجمالى حافز الانتاج, dtype: float64

In [ ]:
df_filtered.head()

,كود المنطقة,كود الادارة,الادارة,الكود,الاسم,الجنسية,الوظيفة,اسم الجهة/الفرع,المعاملة الضريبية,مدة العمل,...,العلاوه الخاصه 7/2025,مجموع العلاوات الخاصة 7/2025,salary_category,deduction_ratio,total_allowances,total_salaries,total_deductions,employee_numbers,employee_counts,Employees_by_dpt
1,1,4,الشئون الأدارية,260,عبدالرؤوف عبدالحميد السعدني,1,مدير إدارة شئون العاملين والوثائق والمحفوظات,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,137.60750,1373.69750,Meduim,50.18%,487091.265618,2.967798e+06,434053.818179,512,512,NaN
2,1,4,الشئون الأدارية,881,فاتن عبدالرحمن محمد,1,أخصائي شئون عاملين أول,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,138.66500,1527.98500,low,nan%,487091.265618,2.967798e+06,434053.818179,512,512,NaN
3,1,4,الشئون الأدارية,1064,سعيد محمد عبد الله,1,سائق أول,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,145.63700,1503.87700,HIGH,21.18%,487091.265618,2.967798e+06,434053.818179,512,512,NaN
4,1,4,الشئون الأدارية,2301,حسن فؤاد أحمد محمد,1,عامل خدمات رابع,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,60.60266,737.53266,HIGH,10.65%,487091.265618,2.967798e+06,434053.818179,512,512,NaN
5,1,4,الشئون الأدارية,2530,عايدة خطاب ابراهيم,1,أخصائي تخطيط ثالث,شركة قها للأغذية المحفظة / مصنع الرأس السوداء,1.0,30.0,...,72.45077,819.54077,HIGH,11.03%,487091.265618,2.967798e+06,434053.818179,512,512,NaN

In [ ]:
#موظف صاحب اعلي جزاءات
df_filtered.groupby('الاسم')['الجزاءات\nس'].sum().nlargest(2)

الاسم
علي محمود علي أحمد                5.0
رمضان محمود هاشم                  2.0
Name: الجزاءات\nس, dtype: float64

In [ ]:
#موظف صاحب اعلي استقطاعات
df_filtered.groupby('الاسم')['اجمالى الأستقطاعات'].sum().nlargest(1)

الاسم
محمد صلاح أنور رمضان              5084.35813
Name: اجمالى الأستقطاعات, dtype: float64

In [ ]:
#الموظفين اصحاب اعلي جزاءات
df_filtered[df_filtered['اجمالى الأستقطاعات']>0].groupby('الاسم')['اجمالى الأستقطاعات'].sum().nlargest(5)

الاسم
محمد صلاح أنور رمضان              5084.358130
فاتن علي حسين سليمان              4664.455962
حمدي محمد يونس محمد               4346.836447
حنان حسن على العفيفى              4301.828775
أيمن افرام ثان منصور              4143.092554
Name: اجمالى الأستقطاعات, dtype: float64

In [ ]:
# ( not zero )الموظفين اصحاب اقل جزاءات
df_filtered[df_filtered['اجمالى الأستقطاعات'] >0].groupby('الاسم')['اجمالى الأستقطاعات'].sum().nsmallest(5)

الاسم
سوسن عبد الرحيم توفيق             159.112950
جيهان مختار عبده                  262.949675
عواطف أحمد بهلول أحمد             379.718994
أسماء محمد محمد ربيع              380.956482
فاطمة رمضان محمد                  431.013142
Name: اجمالى الأستقطاعات, dtype: float64

In [ ]:
#متوسط الرواتب في الشركة
df['صافى الراتب'].mean()
print ('Avg Salaries=', df_filtered['صافى الراتب'].mean())

Avg Salaries= 4977.886157459959

In [ ]:
#الوسيط بالنسبة للرواتب
df_filtered['صافى الراتب'].median()
print('median of salaries=', df_filtered['صافى الراتب'].median())

median of salaries= 5565.2613249999995

In [ ]:
import plotly.express as px
import arabic_reshaper
from bidi.algorithm import get_display

In [ ]:
def fix_arabic(text_values):
  return get_display(arabic_reshaper.reshape(text_values))

In [ ]:
fig=px.line(Employees_by_dpt)
fig.update_layout(
    template="plotly_white",
    title_font_size=40,
    xaxis_title="departments",
    yaxis_title="count of employees",
    title="Employees by departments")

fig.show()

In [ ]:
dept_salaries_insights=df.groupby('الادارة').agg({'total_salaries': 'sum', 'total_deductions': 'sum', 'total_allowances': 'sum'})
print(dept_salaries_insights)

                      total_salaries  total_deductions  total_allowances
الادارة
ألبان دمياط             1.780679e+07      2.604323e+06      2.922548e+06
الأدارة المالية         5.045256e+07      7.378915e+06      8.280552e+06
الأمن و الحراسة         7.419495e+07      1.085135e+07      1.217728e+07
الاحتياجات              8.903394e+07      1.302161e+07      1.461274e+07
الامن الصناعى           2.671018e+07      3.906484e+06      4.383821e+06
التبريدات               2.671018e+07      3.906484e+06      4.383821e+06
التجميد                 5.045256e+07      7.378915e+06      8.280552e+06
التجهيز و التعبئة       8.903394e+06      1.302161e+06      1.461274e+06
التشغيل الهندسي         7.419495e+07      1.085135e+07      1.217728e+07
التغليف                 9.496953e+07      1.388972e+07      1.558692e+07
الحسابات                5.935596e+06      8.681076e+05      9.741825e+05
الحضانة                 4.154917e+07      6.076753e+06      6.819278e+06
الشئون الأدارية         8.013054e+07      1.171945e+07      1.315146e+07
الشئون القانونية        1.187119e+07      1.736215e+06      1.948365e+06
الصيانة                 5.935596e+06      8.681076e+05      9.741825e+05
القسم الهندسي           3.858137e+07      5.642700e+06      6.332186e+06
القفل                   1.187119e+07      1.736215e+06      1.948365e+06
المبيعات                1.483899e+07      2.170269e+06      2.435456e+06
جودة المعمل             2.967798e+06      4.340538e+05      4.870913e+05
سكرتارية                8.903394e+06      1.302161e+06      1.461274e+06
سيارات نقل              2.967798e+06      4.340538e+05      4.870913e+05
مؤقتين أحتياجات         4.748477e+07      6.944861e+06      7.793460e+06
مؤقتين أمن صناعي        8.903394e+06      1.302161e+06      1.461274e+06
مؤقتين أمن و حراسة      2.671018e+07      3.906484e+06      4.383821e+06
مؤقتين الحضانة          3.561357e+07      5.208646e+06      5.845095e+06
مؤقتين الزجاج           2.671018e+07      3.906484e+06      4.383821e+06
مؤقتين الصفيح           2.077459e+07      3.038377e+06      3.409639e+06
مؤقتين القسم الهندسي    1.780679e+07      2.604323e+06      2.922548e+06
مؤقتين المرتجعات        2.967798e+06      4.340538e+05      4.870913e+05
مؤقتين بضاعة جاهزة      8.903394e+06      1.302161e+06      1.461274e+06
مؤقتين تبريدات          2.967798e+06      4.340538e+05      4.870913e+05
مؤقتين تجميد            2.967798e+07      4.340538e+06      4.870913e+06
مؤقتين تشغيل هندسي      1.187119e+07      1.736215e+06      1.948365e+06
مؤقتين تغليف            3.858137e+07      5.642700e+06      6.332186e+06
مؤقتين شئون أدارية      5.342036e+07      7.812969e+06      8.767643e+06
مؤقتين مالية            2.967798e+07      4.340538e+06      4.870913e+06
مؤقتين مبيعات           1.483899e+07      2.170269e+06      2.435456e+06
مؤقتين معامل و بحوث     4.154917e+07      6.076753e+06      6.819278e+06
مؤقتين معلبات أ         2.967798e+07      4.340538e+06      4.870913e+06
مؤقتين معلبات ب         4.154917e+07      6.076753e+06      6.819278e+06
مؤقتين مكتب القاهرة     8.903394e+06      1.302161e+06      1.461274e+06
مستلزمات الانتاج        1.483899e+07      2.170269e+06      2.435456e+06
مصنع الزجاج             2.374238e+07      3.472431e+06      3.896730e+06
مصنع الصفيح             5.045256e+07      7.378915e+06      8.280552e+06
مصنع معلبات أ           6.825935e+07      9.983238e+06      1.120310e+07
مصنع معلبات ب           5.638816e+07      8.247023e+06      9.254734e+06
معامل و بحوث            4.154917e+07      6.076753e+06      6.819278e+06
مكتب أسيوط              2.967798e+06      4.340538e+05      4.870913e+05
مكتب القاهرة            1.483899e+07      2.170269e+06      2.435456e+06

In [ ]:
dept_summary = df.groupby('الادارة').agg(
    Employees_by_dpt=('الاسم', 'count'),
    avg_salary=('صافى الراتب', 'mean')).sort_values(by='Employees_by_dpt', ascending=False)

In [ ]:
dept_summary.sort_values(by='avg_salary')

                      Employees_by_dpt   avg_salary
الادارة
اجمالى جودة المعمل                   1     0.000000
جودة المعمل                          1     0.000000
الصيانة                              2     0.000000
اجمالى مؤقتين دمياط                  1     0.000000
اجمالى الصيانة                       1     0.000000
اجمالى القفل                         1     0.000000
القفل                                4     0.000000
المبيعات                             5  2794.289656
الشئون القانونية                     4  2797.721826
سكرتارية                             3  2798.528839
ألبان دمياط                          6  2866.264140
مستلزمات الانتاج                     5  3410.684834
الأدارة المالية                     17  3671.561250
الشئون الأدارية                     27  3954.311875
معامل و بحوث                        14  4355.015279
مصنع الزجاج                          8  4436.834490
الاحتياجات                          30  4467.822996
التغليف                             32  4486.661360
الامن الصناعى                        9  4801.212975
مصنع الصفيح                         17  4969.201192
التشغيل الهندسي                     25  5044.936502
مكتب أسيوط                           1  5082.943702
مصنع معلبات ب                       19  5136.334176
مؤقتين الصفيح                        7  5260.167956
مؤقتين مالية                        10  5302.243712
مؤقتين معامل و بحوث                 14  5341.774801
مؤقتين معلبات أ                     10  5346.769606
مؤقتين تغليف                        13  5355.154272
مصنع معلبات أ                       23  5413.651695
مؤقتين الزجاج                        9  5445.484522
مؤقتين تشغيل هندسي                   4  5447.742540
القسم الهندسي                       13  5453.502957
مؤقتين أمن صناعي                     3  5475.517092
التجميد                             17  5488.583970
مؤقتين شئون أدارية                  18  5529.064336
مؤقتين القسم الهندسي                 6  5562.587785
الحضانة                             14  5592.607994
مؤقتين أحتياجات                     16  5612.752278
مكتب القاهرة                         6  5657.232238
مؤقتين المرتجعات                     1  5670.321387
مؤقتين معلبات ب                     14  5717.328445
مؤقتين مكتب القاهرة                  3  5740.097635
مؤقتين الحضانة                      12  5762.964812
مؤقتين تجميد                        10  5764.681923
الأمن و الحراسة                     25  5770.339000
مؤقتين بضاعة جاهزة                   3  5841.577884
مؤقتين مبيعات                        5  5842.916487
مؤقتين أمن و حراسة                   9  6007.656832
التجهيز و التعبئة                    3  6028.482116
مؤقتين تبريدات                       1  6095.361148
الحسابات                             2  6095.931427
التبريدات                            9  6195.702014
سيارات نقل                           1  6318.181757
أسم العامل                           2          NaN

In [ ]:
avg_salary=df_filtered.groupby('الادارة')['صافى الراتب'].mean().sort_values(ascending=False)

In [ ]:


fig=px.bar(avg_salary)
fig.update_layout(title='متوسط الرواتب في كل ادارة', xaxis_title='الادارة', yaxis_title='متوسط الراتب')
fig.update_traces(textposition='outside')
fig.show()

In [ ]:
salary_category=df_filtered['salary_category'].count()

In [ ]:
employee_counts=df_filtered['الاسم'].value_counts()
employee_counts=len(employee_counts)

In [ ]:
df['employee_counts']=employee_counts

In [ ]:
salaries_by_employees=df.groupby('salary_category')['employee_counts'].sum()

In [ ]:
salaries_by_employees=df.groupby('salary_category')['employee_counts'].count()

In [ ]:
df['employee_numbers']=employee_numbers

In [ ]:
fig=px.pie(salaries_by_employees, values='employee_counts', names=salaries_by_employees.index, title='عدد الموظفين حسب الراتب')

fig.update_traces(textposition='outside')
fig.show()

In [ ]:
filtered_numeric_values=df_filtered.select_dtypes(include='number')

In [ ]:
filtered_numeric_values

,المعاملة الضريبية,مدة العمل,الحالة التأمينية,الرقم التأمينى,تاريخ الالتحاق بالتأمينات,الضرائب المراد خصمها,صندوق الشهداء,علاوات خاصة معفاة,الاساسي المجرد من العلاوات,الأساسي,...,مجموع العلاوات 10%&%5%,فرق 150,العلاوه الخاصه 7/2025,مجموع العلاوات الخاصة 7/2025,total_allowances,total_salaries,total_deductions,employee_numbers,employee_counts,Employees_by_dpt
1,1.0,30.0,1.0,42046291.0,19891108.0,NaN,6.15,687.99,2339.37500,3027.36500,...,412.822500,0.0,137.607500,1373.697500,487091.265618,2.967798e+06,434053.818179,512,512,NaN
2,1.0,30.0,1.0,NaN,19940702.0,NaN,0.00,NaN,NaN,3050.63000,...,415.995000,0.0,138.665000,1527.985000,487091.265618,2.967798e+06,434053.818179,512,512,NaN
3,1.0,30.0,1.0,5019965.0,19821230.0,NaN,6.15,733.04,2470.97400,3204.01400,...,436.911000,0.0,145.637000,1503.877000,487091.265618,2.967798e+06,434053.818179,512,512,NaN
4,1.0,30.0,1.0,57905216.0,20120301.0,NaN,4.22,374.26,958.99852,1333.25852,...,181.807980,0.0,60.602660,737.532660,487091.265618,2.967798e+06,434053.818179,512,512,NaN
5,1.0,30.0,1.0,53039637.0,20111030.0,NaN,4.20,475.04,1118.87694,1593.91694,...,217.352310,0.0,72.450770,819.540770,487091.265618,2.967798e+06,434053.818179,512,512,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,1.0,30.0,1.0,30492916.0,19930501.0,NaN,NaN,755.06,2661.08900,3416.14900,...,465.838500,0.0,155.279500,1521.869500,487091.265618,2.967798e+06,434053.818179,512,512,NaN
506,1.0,30.0,1.0,43155295.0,19890203.0,NaN,NaN,712.75,2440.05900,3152.80900,...,429.928500,0.0,143.309500,1422.739500,487091.265618,2.967798e+06,434053.818179,512,512,NaN
507,1.0,30.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2979.79000,...,406.335000,0.0,135.445000,1426.295000,487091.265618,2.967798e+06,434053.818179,512,512,NaN
508,1.0,30.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,3027.60700,...,412.855500,0.0,137.618500,1446.178500,487091.265618,2.967798e+06,434053.818179,512,512,NaN
509,1.0,30.0,1.0,37729512.0,20040420.0,NaN,NaN,420.28,1363.23987,1783.51987,...,243.207255,0.0,81.069085,890.549085,487091.265618,2.967798e+06,434053.818179,512,512,NaN

In [ ]:
def fix_arabic(text):
  return get_display(arabic_reshaper.reshape(text))

In [ ]:
def dix_arabic(text_values):
  return get_display(arabic_reshaper.reshape(text_values))

In [ ]:
dept_summary = df.groupby('الادارة').agg(
    Employees_by_dpt=('الاسم', 'count'),
    avg_salary=('صافى الراتب', 'mean')).sort_values(by='Employees_by_dpt', ascending=False)

In [ ]:
top_5_dpt_by_Employees=dept_summary.nlargest(5,'Employees_by_dpt')
print(top_5_dpt_by_Employees)

                 Employees_by_dpt   avg_salary
الادارة
التغليف                        32  4486.661360
الاحتياجات                     30  4467.822996
الشئون الأدارية                27  3954.311875
التشغيل الهندسي                25  5044.936502
الأمن و الحراسة                25  5770.339000

In [ ]:
dept_summary

                      Employees_by_dpt   avg_salary
الادارة
التغليف                             32  4486.661360
الاحتياجات                          30  4467.822996
الشئون الأدارية                     27  3954.311875
الأمن و الحراسة                     25  5770.339000
التشغيل الهندسي                     25  5044.936502
مصنع معلبات أ                       23  5413.651695
مصنع معلبات ب                       19  5136.334176
مؤقتين شئون أدارية                  18  5529.064336
التجميد                             17  5488.583970
الأدارة المالية                     17  3671.561250
مصنع الصفيح                         17  4969.201192
مؤقتين أحتياجات                     16  5612.752278
مؤقتين معلبات ب                     14  5717.328445
الحضانة                             14  5592.607994
معامل و بحوث                        14  4355.015279
مؤقتين معامل و بحوث                 14  5341.774801
القسم الهندسي                       13  5453.502957
مؤقتين تغليف                        13  5355.154272
مؤقتين الحضانة                      12  5762.964812
مؤقتين تجميد                        10  5764.681923
مؤقتين مالية                        10  5302.243712
مؤقتين معلبات أ                     10  5346.769606
الامن الصناعى                        9  4801.212975
مؤقتين أمن و حراسة                   9  6007.656832
مؤقتين الزجاج                        9  5445.484522
التبريدات                            9  6195.702014
مصنع الزجاج                          8  4436.834490
مؤقتين الصفيح                        7  5260.167956
مكتب القاهرة                         6  5657.232238
مؤقتين القسم الهندسي                 6  5562.587785
ألبان دمياط                          6  2866.264140
مؤقتين مبيعات                        5  5842.916487
مستلزمات الانتاج                     5  3410.684834
المبيعات                             5  2794.289656
القفل                                4     0.000000
الشئون القانونية                     4  2797.721826
مؤقتين تشغيل هندسي                   4  5447.742540
التجهيز و التعبئة                    3  6028.482116
سكرتارية                             3  2798.528839
مؤقتين أمن صناعي                     3  5475.517092
مؤقتين مكتب القاهرة                  3  5740.097635
مؤقتين بضاعة جاهزة                   3  5841.577884
الصيانة                              2     0.000000
الحسابات                             2  6095.931427
أسم العامل                           2          NaN
اجمالى مؤقتين دمياط                  1     0.000000
اجمالى الصيانة                       1     0.000000
اجمالى القفل                         1     0.000000
اجمالى جودة المعمل                   1     0.000000
جودة المعمل                          1     0.000000
مؤقتين تبريدات                       1  6095.361148
مؤقتين المرتجعات                     1  5670.321387
سيارات نقل                           1  6318.181757
مكتب أسيوط                           1  5082.943702

In [ ]:
min_salary=(df['صافى الراتب']<=3000).value_counts()

In [ ]:
min_salary,max_salary=df['صافى الراتب'].min(),df['صافى الراتب'].max()
print('min salary=',min_salary)
print('max salary=',max_salary)

min salary= 0.0
max salary= 8958.235364285714

In [ ]:
top_5_dept = df.groupby( 'الادارة')[ 'صافى الراتب'].sum().nlargest(5).reset_index().sort_values(by='صافى الراتب', ascending=False)
print(top_5_dept)

           الادارة    صافى الراتب
0  الأمن و الحراسة  144258.474991
1          التغليف  143573.163533
2       الاحتياجات  134034.689877
3  التشغيل الهندسي  126123.412539
4    مصنع معلبات أ  124513.988994

In [ ]:
top5_dep=df[['صافى الراتب','الادارة']].nlargest(5,'صافى الراتب')
print(top5_dep)

     صافى الراتب            الادارة
94   8958.235364          التبريدات
142  7907.446944      القسم الهندسي
276  7443.725172    التشغيل الهندسي
318  7333.729433  التجهيز و التعبئة
107  7264.751250         الاحتياجات

In [ ]:
fig=px.bar(top_5_dept,x='الادارة', y= 'صافى الراتب', color='الادارة', text='صافى الراتب', title='Top 5 Deprtments costly by Total Salaries')
fig.update_traces(textposition='outside')
fig.show()

In [ ]:
fig=px.bar(top5_dep, x='الادارة',y='صافى الراتب',color='الادارة',color_continuous_scale='green', text='صافى الراتب', title='Top 5 Departments by Net Salary')
fig.update_traces(textposition='outside')
fig.show()

In [ ]:
#boxplot to see outliers in net salaries
fig=px.box(df_filtered['صافى الراتب'], title= ' dedecting outliers in salaries')


fig.show()

In [ ]:
#removing outliers
q1=df_filtered['صافى الراتب'].quantile(0.25)
q3=df_filtered['صافى الراتب'].quantile(0.75)

print('q1=',q1)
print('q3=',q3)

iqr=q3-q1
print('iqr=', iqr)

lower_bound= q1-1.5*iqr
upper_bound=q3+1.5*iqr

print('lower bound=', lower_bound)
print('upper bound=', upper_bound)

q1= 4974.6830433333325
q3= 5874.118043333334
iqr= 899.4350000000013
lower bound= 3625.5305433333306
upper bound= 7223.270543333336

In [ ]:
df_filtered_new=df_filtered[(df_filtered['صافى الراتب']>=lower_bound) & (df_filtered['صافى الراتب']<=upper_bound)]

In [190]:
total_salaries=df['صافى الراتب'].sum()
total_deductions=df['اجمالى الأستقطاعات'].sum()
total_allowances=df['اجمالى حافز الانتاج'].sum()

In [191]:
total_allowances

np.float64(487091.26561848895)

In [239]:
salary_category_bydep=df.groupby(['الادارة','salary_category']).size().reset_index(name='employee_counts')

In [240]:
fig=px.bar(salary_category_bydep, x='الادارة', y='employee_counts', color='salary_category', barmode='stack',
           color_discrete_map={'HIGH': 'skyblue', 'Meduim': 'yellow', 'low': 'green'},
           title='Number of Employees by Salary Category and Department')
fig.show()